export const packages = [
  {
    id: "basic",
    name: "Basic",
    icon: "⭐",
    tokens: 500,
    price: "$5",
    color: "#3b82f6",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 20, maxFileSizeMB: 50 },
    description: "Full access to all tools",
  },
  {
    id: "standard",
    name: "Standard",
    icon: "💎",
    tokens: 1500,
    price: "$15",
    color: "#a855f7",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 50, maxFileSizeMB: 100 },
    description: "Full retouch and background suite",
  },
  {
    id: "pro",
    name: "Pro",
    icon: "🚀",
    tokens: 4000,
    price: "$40",
    color: "#f59e0b",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 200, maxFileSizeMB: 100 },
    description: "Everything unlocked for professional workflows",
  },
  {
    id: "studio",
    name: "Studio",
    icon: "🏆",
    tokens: 12000,
    price: "$120",
    color: "#ec4899",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 999, maxFileSizeMB: 100 },
    description: "Full platform access including all future panels",
  },
]
