export const packages = [
  {
    id: "starter",
    name: "Starter",
    icon: "🌱",
    tokens: 10,
    price: "$2",
    color: "#22c55e",
    panels: ["retouch"],
    actions: ["quick_enhance", "batch_retouch"],
    limits: { maxBatchSize: 5, maxFileSizeMB: 10 },
    description: "Perfect for trying out portrait retouching",
  },
  {
    id: "basic",
    name: "Basic",
    icon: "⭐",
    tokens: 50,
    price: "$8",
    color: "#3b82f6",
    panels: ["retouch", "background"],
    actions: ["quick_enhance", "batch_retouch", "advanced_edit", "bg_remove", "bg_replace_solid", "bg_blur"],
    limits: { maxBatchSize: 20, maxFileSizeMB: 50 },
    description: "Retouch and background tools for everyday use",
  },
  {
    id: "standard",
    name: "Standard",
    icon: "💎",
    tokens: 100,
    price: "$15",
    color: "#a855f7",
    panels: ["retouch", "background"],
    actions: ["quick_enhance", "batch_retouch", "advanced_edit", "bg_remove", "bg_replace_solid", "bg_blur", "bg_ai_generate", "bg_expand", "bg_flux_preset", "bg_replace"],
    limits: { maxBatchSize: 50, maxFileSizeMB: 100 },
    description: "Full retouch and background suite",
  },
  {
    id: "pro",
    name: "Pro",
    icon: "🚀",
    tokens: 300,
    price: "$40",
    color: "#f59e0b",
    panels: ["retouch", "background"],
    actions: "all",
    limits: { maxBatchSize: 200, maxFileSizeMB: 100 },
    description: "Everything unlocked for professional workflows",
  },
  {
    id: "studio",
    name: "Studio",
    icon: "🏆",
    tokens: 1000,
    price: "$120",
    color: "#ec4899",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 999, maxFileSizeMB: 100 },
    description: "Full platform access including all future panels",
  },
]
