export const packages = [
  {
    id: "basic",
    name: "Basic",
    icon: "⭐",
    tokens: 500,
    price: "$5",
    color: "#8c8a82",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 20, maxFileSizeMB: 50 },
    description: "Full access to all tools",
  },
  {
    id: "standard",
    name: "Standard",
    icon: "💎",
    tokens: 1500,
    price: "$15",
    color: "#c5a572",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 50, maxFileSizeMB: 100 },
    description: "Full retouch and background suite",
  },
  {
    id: "pro",
    name: "Pro",
    icon: "🚀",
    tokens: 4000,
    price: "$40",
    color: "#b8863b",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 200, maxFileSizeMB: 100 },
    description: "Everything unlocked for professional workflows",
  },
  {
    id: "studio",
    name: "Studio",
    icon: "🏆",
    tokens: 12000,
    price: "$120",
    color: "#a06a78",
    panels: "all",
    actions: "all",
    limits: { maxBatchSize: 999, maxFileSizeMB: 100 },
    description: "Full platform access including all future panels",
  },
]
